### ISSUE TITLE
Snippet delete is not working 

### ISSUE THREAD

**Issue by sadeq-qafari** [Snipet-ir/Snippet2#38]
You can see related error in console when trying to delete a snippet:
````
Uncaught ReferenceError: alertify is not defined
    at HTMLButtonElement.deleteSnippetHandler (index.js?v=2.2.0:556:2)
    at HTMLButtonElement.dispatch (jquery-3.5.1.min.js:2:43090)
    at v.handle (jquery-3.5.1.min.js:2:41074)
````

**Comment by ehcaning** [comment]
@sadeq-qafari Thanks for reporting, it's resolved now ✅

**Comment by sadeq-qafari** [comment]
@ehcaning your welcome.
